apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: vault-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault-example
      annotations:
        vaultproject.io/policies: default
        vaultproject.io/ttl: "24h"
        pod.alpha.kubernetes.io/init-containers: '[
          {
            "name": "vault-init",
            "image": "docker.io/kelseyhightower/vault-init:0.0.1",
            "imagePullPolicy": "Always",
            "env": [
              {
                "name": "POD_NAME",
                "valueFrom": {"fieldRef": {"fieldPath": "metadata.name"}}
              },
              { 
                "name": "POD_NAMESPACE",
                "valueFrom": {"fieldRef": {"fieldPath": "metadata.namespace"}}
              },
              { 
                "name": "VAULT_ADDR",
                "value": "http://vault.vault-controller.svc.cluster.local:8200"
              },
              { 
                "name": "VAULT_CONTROLLER_ADDR",
                "value": "http://vault-controller.vault-controller.svc.cluster.local"
              }
            ],
            "volumeMounts": [
              {
                "name": "vault-tokens",
                "mountPath": "/var/run/secrets/vaultproject.io"
              }
            ]
          }
        ]'
    spec:
      containers:
        - name: vault-example
          image: "docker.io/kelseyhightower/vault-example:0.0.1"
          imagePullPolicy: Always
          env:
            - name: "VAULT_ADDR"
              value: "http://vault.vault-controller.svc.cluster.local:8200"
          volumeMounts:
            - name: vault-tokens
              mountPath: "/var/run/secrets/vaultproject.io"
      serviceAccountName: vault-example
#      serviceAccountName: vault
      volumes:
        - name: vault-tokens
          emptyDir: {}
